name: 'Tag release for latest major version'

on:
  release:
    types: [published, edited]

permissions:
  contents: write

jobs:
  actions-tagger:
    runs-on: ubuntu-latest
    permissions:
      deployments: write
    steps:
      - uses: Actions-R-Us/actions-tagger@v2
